baseURL = "https://iamlenavollmer.com/"
languageCode = "en"
title = "iamlenavollmer"
theme = "coder"

[params]
    author = "Lena Vollmer"
    description = "Lena Vollmer's personal website"
    keywords = "books,blog,food,developer,personal"
    info = "Web Developer and Bookworm"
    avatarurl = "avatar.png"
    #gravatar = "john.doe@example.com"
    #footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []


[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/lenavollmer"
#[[params.social]]
    #name = "Gitlab"
    #icon = "fab fa-gitlab"
    #weight = 2
    #url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/lena-vollmer-59b9a9123/?locale=en_US"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 6
    url = "https://www.instagram.com/thesearethebooks/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            # [[languages.en.menu.main]]
            # name = "Blog"
            # weight = 2
            # url = "posts/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "projects/"

            # [[languages.en.menu.main]]
            # name = "Contact me"
            # weight = 5
            # url = "contact/"